spring.application.name=backend

# ✅ VERY IMPORTANT (Render port fix)
server.port=${PORT:8080}

# ✅ Faster startup (reduces 502)
spring.main.lazy-initialization=true
spring.jpa.open-in-view=false

# ❗ TEMP: Disable DB (to make app start reliably first)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ===== EMAIL CONFIG =====
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f6ca670e1716d9
spring.mail.password=d63a64b22fdb4e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
