spring.application.name=backend

server.port=${PORT:8080}

spring.main.lazy-initialization=true
spring.jpa.open-in-view=false

# DATABASE
spring.datasource.url=jdbc:postgresql://dpg-d7div3svikkc73e5lhjg-a.virginia-postgres.render.com:5432/campus_hub_db_i333?sslmode=require
spring.datasource.username=campus_hub_db_i333_user
spring.datasource.password=jWAXMpplChWeDQ00bYMUWgkW4xwkaSXt
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# EMAIL
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f6ca670e1716d9
spring.mail.password=d63a64b22fdb4e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
