spring.application.name=backend

server.port=${PORT:8080}

spring.main.lazy-initialization=true
spring.jpa.open-in-view=false

# DATABASE
spring.datasource.url=jdbc:postgresql://dpg-d899pph9rddc7393f5fg-a.virginia-postgres.render.com:5432/event_hub_db_dt9f
spring.datasource.username=event_hub_db_dt9f_user
spring.datasource.password=FNJvtnWXUt7vHDqU9SrKjstT4SCO4LsQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# EMAIL
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f6ca670e1716d9
spring.mail.password=d63a64b22fdb4e

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
